server.port: 8081
spring.kafka.producer.bootstrap-servers=localhost: 9092

spring:
  kafka:
    consumer:
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092